Added pyls.extraSysPath. Fixes #381
palantir/python-language-server pull request #382
Opened 2018-06-21 16:51 UTC by Kronuz

This adds `extraSysPath` to extend `extra_sys_path` passed to Jedi.

2018-08-26 17:31 UTC, gatesn requested changes
Think we should have `settings.get('extraSysPath', []) + self.source_roots(path)`

2018-08-26 17:31 UTC, gatesn commented on pyls/workspace.py
> +        extra_sys_path.extend(settings.get('extraSysPath', []))
Extend? Or prepend? I wonder if an explicit config override should be put at the front of the sys path

2019-05-23 17:24 UTC, gagbo commented
Should the work on this start again, would this be merged ? I don't understand why it stalled exactly, and this is exactly the feature I'm missing.

I think I prefer prepending the extra_sys_path (or maybe give one after and one before options), because I would want to put specific `PYTHONPATH` values here, which are inserted early in `sys.path()` when running a python program. Especially when, as @gatesn says, it is an override.

2019-12-24 15:11 UTC, ccordoba12 commented
This was implemented in PR #680.

2019-12-24 15:11 UTC, closed without merging