Implement 'range' property for hover response
palantir/python-language-server pull request #485
Opened 2019-02-05 16:01 UTC by vhakulinen

Include `range` property for the `textDocument/hover` response: https://microsoft.github.io/language-server-protocol/specification#textDocument_hover.

2019-02-05 16:01 UTC, palantirtech commented
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @vhakulinen! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2019-02-15 10:40 UTC, gatesn requested changes
Thank you for this contribution, really nice. Couple of small comments then should be good to go

2019-02-15 10:40 UTC, gatesn commented on pyls/plugins/hover.py
> +        'range': pos,
Can you inline `pos` here

2019-02-15 10:40 UTC, gatesn commented on pyls/plugins/hover.py
> +import json
Unused?

2019-02-15 10:40 UTC, gatesn commented on pyls/workspace.py
> +        line = self.lines[position['line']]
Can you add a test for this method explicitly?

2019-02-28 08:45 UTC, gatesn commented
Copying over to a local branch so I can finish up the changes

2019-02-28 08:45 UTC, merged

2019-02-28 08:49 UTC, vhakulinen commented
Sorry, I completely forgot this while doing other stuff.