Do  not install plugin tests
palantir/python-language-server pull request #495
Opened 2019-02-10 22:20 UTC by lo-ca

2019-02-10 22:20 UTC, palantirtech commented
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @lo-ca! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2019-02-15 09:52 UTC, gatesn requested changes
Thank you, this is a good catch! Let's wildcard everything though

2019-02-15 09:52 UTC, gatesn commented on setup.py
> +    packages=find_packages(exclude=['contrib', 'docs', 'test', 'test.plugins']),
Can you change this to `test.*`?

2019-03-27 08:49 UTC, gatesn commented
Closed in #493

2019-03-27 08:49 UTC, closed without merging