[fix] explicitly define our `TestDocumentSync` capabilities
palantir/python-language-server pull request #613
Opened 2019-07-02 09:54 UTC by mpanarin

According to specification, passing a number in `TextDocumentSync` is for legacy support. I think we should move to an explicit declaration of capabilites, as modern clients require that (ex. Emacs lsp-mode will not send notifications that are not defined in capabilities, which is correct, imo).

2019-07-02 09:54 UTC, palantirtech commented
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @mpanarin! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2019-07-02 11:49 UTC, ccordoba12 commented
@andfoy, please take a look at this one.

2019-07-02 12:41 UTC, gatesn approved these changes

2019-07-02 12:43 UTC, gatesn requested changes

2019-07-02 12:43 UTC, gatesn commented on pyls/python_ls.py
> +            'textDocumentSync': {
I think we want `openClose: true` as well

2019-07-02 12:48 UTC, mpanarin commented
@gatesn oops, updated.

2019-07-15 07:54 UTC, mpanarin commented
@ccordoba12 
ping. As I addressed the comment by @gatesn 
Maybe this can be merged?

2019-07-15 07:58 UTC, ccordoba12 commented
You're right, thanks for the reminder.

2019-07-15 07:59 UTC, merged