Don't go to definition of builtin modules
palantir/python-language-server pull request #687
Opened 2019-10-31 15:01 UTC by jackwickham

If you do Go To Definition (F12 in vscode) on a string, it opens the builtins.pyi file for python 3, because the definition is not being filtered properly.

This PR corrects that behaviour so that neither python 2 nor 3 will go to the builtins file.

2019-10-31 15:59 UTC, jackwickham commented
If going to builtin definitions would be desirable for some people then it could be made configurable, but I'm not sure if that's necessary.

2019-10-31 16:23 UTC, gatesn requested changes

2019-10-31 16:23 UTC, gatesn commented on test/plugins/test_definitions.py
> +    assert [] == pyls_definitions(config, doc, cursor_pos)
Should be `assert not pyls_definitions(config, doc, cursor_pos)`

2019-10-31 16:23 UTC, gatesn commented on pyls/plugins/definition.py
> +        if d.is_definition() and d.line is not None and d.column is not None and
Can you pull this out into a function? It doesn't read very clearly anymore

2019-10-31 16:41 UTC, gatesn commented on pyls/plugins/definition.py
> +def not_internal_definition(definition):
Prefix with `_` :)

2019-11-01 11:26 UTC, gatesn approved these changes

2019-11-01 11:26 UTC, merged